language: cpp
compiler:
    - clang

before_install:
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq
    - sudo apt-get install cmake
    - sudo add-apt-repository -y ppa:h-rayflood/llvm
    - sudo apt-get update -qq

install:
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4
  - export CXX="clang++-3.4"

script:
  - cd src
  - bash run_tests.sh

